enum class PageIndex {
    HELP,
    FIRST_TIME_VISITOR_GUIDE,
    ESTIMATED_TIME,
    SQUIBBING,
    PARKING,
    ROAD_CLOSURE,
    PLANNER,
    DAYTIME_ENTERTAINMENT,
    GALLERY,
    VOTING,
    VOTINGRESULTS,
    SOCIAL_MEDIA,
    APP_INFO,
    NEWS,
    VIDEOS
} 